spring:
  datasource:
    url: jdbc:h2:D:/Project/SpringCloud/my-spring-cloud-service/servicedb;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
